general:
  delete_log_file_at_start: true
  callsign: XXXXX # Log4OM Callsign used to check if you get spotted by someone
  log_to_file: true
  log_level: INFO # INFO or DEBUG or WARN
  telnetserver: true # not in use for now
  flexradiospot: true
  sendFreqModeToLog4OM: true # if not using a Flex then turn this on to send Freq and Mode to Log4OM which should in turn change the freq on the radio
  # Spot colors, if empty then default, colors in HEX AARRGGBB format
  spot_color_new_entity:
  background_color_new_entity:
  spot_color_new_band:
  background_color_new_band:
  spot_color_new_mode:
  background_color_new_mode:
  spot_color_new_band_mode:
  background_color_new_band_mode:
  spot_color_new_slot:
  background_color_new_slot:
  spot_color_my_callsign:
  background_color_my_callsign:
  spot_color_worked:
  background_color_worked:
database:
  mysql: false #only one of the two can be true
  sqlite: true
  mysql_db_user: xxxx
  mysql_db_password: xxxxxxxx
  mysql_db_name: xxxxxxx
  mysql_host: 10.10.10.1
  mysql_port: 3306
sqlite:
  sqlite_path: 'C:\Perso\Seafile\Radio\Logs\Log4OM\F4BPO.SQLite' # SQLite Db path of Log4OM
cluster:
  server: cluster.f4bpo.com # dxc.k0xm.net dxc.sm7iun.se
  port: 7300
  login: f4bpo
  password: xxxxxx # Only if needed
  skimmer: true
  ft8: false
  ft4: false
  beacon: false
  command: "SET/FILTER DOC/PASS 1A,3A,4O,9A,9H,C3,CT,CU,DL,E7,EA,EA6,EI,ER,ES,EU,F,G,GD,GI,GJ,GM,GU,GW,HA,HB,HB0,HV,I,IS,IT9,JW,JX,LA,LX,LY,LZ,OE,OH,OH0,OJ0,OK,OM,ON,OY,OZ,PA,S5,SM,SP,SV,SV5,SV9,T7,TA1,TF,TK,UA,UR,YL,YO,YU,Z6,Z3" #"SET/FILTER DOC/PASS 1A,3A,4O,9A,9H,C3,CT,CU,DL,E7,EA,EA6,EI,ER,ES,EU,F,G,GD,GI,GJ,GM,GU,GW,HA,HB,HB0,HV,I,IS,IT9,JW,JX,LA,LX,LY,LZ,OE,OH,OH0,OJ0,OK,OM,ON,OY,OZ,PA,S5,SM,SP,SV,SV5,SV9,T7,TA1,TF,TK,UA,UR,YL,YO,YU,Z6,Z3,ZA,ZB"
  login_prompt: "login:"
flex:
  discovery: false # Radio must be on same LAN than the program
  ip: 10.10.10.100 # if discovery is true no need to put an IP, can be a public or remote ip
  spot_life: 600 #seconds
telnetserver: # Log4OM must be connected to this server ie: localhost:7301 if on same machine as this program else ip:7301
  host: 0.0.0.0
  port: 7301
gotify:
  enable: false
  url: https://gotify.tld.com/message
  token: xxxxxxxx
  NewDXCC: true
  NewBand: false
  NewMode: false
  NewBandAndMode: false
  Watchlist: false